data "azurerm_billing_enrollment_account_scope" "example" {
 billing_account_name = azurerm_billing_enrollment_account_scope.example.billing_account_name
 enrollment_account_name = azurerm_billing_enrollment_account_scope.example.enrollment_account_name
}
