data "azurerm_servicebus_namespace_authorization_rule" "example" {
 name = azurerm_servicebus_namespace_authorization_rule.example.name
 namespace_name = azurerm_servicebus_namespace_authorization_rule.example.namespace_name
 resource_group_name = azurerm_servicebus_namespace_authorization_rule.example.resource_group_name
}
